version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app

  dev-client-bundle:
    image: local-dev-server
    depends_on:
      - dev-server
    volumes:
      - ./:/data/
    working_dir: /data/
    # tty needed in order for rollup watch to work.
    tty: true
    command: ./development/bundle-client.sh

  dev-https-proxy:
    image: silintl/traefik-https-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./development/cert/:/cert/
    env_file:
      - ./development/https-proxy.local.env

  dev-server:
    build: development/.
    image: local-dev-server
    depends_on:
      - dev-https-proxy
    env_file:
      - development/development.env
    ports:
      - "8080:8080"
    volumes:
      - ./:/data/
    working_dir: /data/
    command: supervisor development/server.js

  do-full-recovery:
    build: recovery/.
    volumes:
      - ./:/data
    working_dir: /data
    command: ./recovery/do-full-recovery.sh

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
