version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app

  do-full-recovery:
    build: recovery/.
    volumes:
      - ./:/data
    working_dir: /data
    command: ./recovery/do-full-recovery.sh

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
